import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // src/components/ui is vendored/regenerated by the shadcn CLI, not
    // hand-authored — don't lint code we don't own the style of, and don't
    // make every `shadcn add`/update require a manual lint-fix pass.
    "src/components/ui/**",
  ]),
]);

export default eslintConfig;
